; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = stationboard
boards_dir = ./boards

[env]
platform = espressif32@6.5.0
board = lilygo-t-displays3
framework = arduino

debug_tool = esp-builtin
upload_protocol = esptool

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DARDUINO_USB_MODE=1
    -DTOUCH_MODULES_CST_MUTUAL

[env:stationboard]
lib_ldf_mode = deep
extra_scripts = 
    pre:generate_stations.py
    pre:fetch_colors.py
    pre:generate_font.py
lib_deps = 
    bblanchon/ArduinoJson
    tzapu/WiFiManager
    bodmer/TFT_eSPI



[env:T-Display-S3-Queue]
build_flags =
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DTOUCH_MODULES_CST_MUTUAL
lib_deps =
    lovyan03/LovyanGFX
lib_ignore =
    GFX Library for Arduino
    TFT_eSPI
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl

[env:T-Display-S3-Gingoduino]
build_flags =
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DTOUCH_MODULES_CST_MUTUAL
lib_deps =
    lovyan03/LovyanGFX
lib_ignore =
    GFX Library for Arduino
    TFT_eSPI
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl

[env:T-Display-S3-Piano-Debug]
build_flags =
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DTOUCH_MODULES_CST_MUTUAL
lib_deps =
    lovyan03/LovyanGFX
lib_ignore =
    GFX Library for Arduino
    TFT_eSPI
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl

[env:T-Display-S3-BLE-Receiver]
build_flags =
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DTOUCH_MODULES_CST_MUTUAL
lib_deps =
    lovyan03/LovyanGFX
lib_ignore =
    GFX Library for Arduino
    TFT_eSPI
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl

[env:T-Display-S3-BLE-Sender]
build_flags =
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DTOUCH_MODULES_CST_MUTUAL
lib_deps =
    lovyan03/LovyanGFX
lib_ignore =
    GFX Library for Arduino
    TFT_eSPI
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl

[env:T-Display-S3-USB-Device]
build_flags =
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DARDUINO_USB_MODE=0
    -DTOUCH_MODULES_CST_MUTUAL
lib_deps =
    lovyan03/LovyanGFX
lib_ignore =
    GFX Library for Arduino
    TFT_eSPI
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl

[env:T-Display-S3-Music-Explorer]
build_flags =
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DTOUCH_MODULES_CST_MUTUAL
lib_deps =
    sauloverissimo/gingoduino
lib_ignore =
    GFX Library for Arduino
    LovyanGFX
    arduino-nofrendo
    Adafruit MPR121
    DabbleESP32
    PCF8575 library
    PCA95x5
    lvgl

